version: '3'
services:
  mongo:
    image: mongo:demo
    volumes:
      - /Users/jmorris2/dev/docker-learning/data:/data/db
  node:
    image: node:demo
    ports:
      - 80:3000
    depends_on:
      - mongo
